// Exportar servicios principales (Solo Supabase)
export { supabaseAuthService } from './supabaseAuthService';
export { supabaseProductService } from './supabaseProductService';
export { supabaseFavoritesService } from './supabaseFavoritesService';
export { supabaseChatService } from './supabaseChatService';
export { supabaseNotificationService } from './supabaseNotificationService';
export { supabaseProfileService } from './supabaseProfileService';
export { supabaseReviewService } from './supabaseReviewService';
export { supabaseContactService } from './supabaseContactService';
export { supabaseImageService } from './supabaseImageService';
export { supabaseRealtimeService } from './supabaseRealtimeService';
export { supabaseGamificationService } from './supabaseGamificationService';